### ISSUE TITLE
Add support for Markdown body translation

### ISSUE THREAD

**Issue by jeremydw** [grow/grow#11]
Currently, only fields and templates can be translated.

**Comment by WillsB3** [comment]
@jeremydw Did you ever get any further with this?

I have some long form copy in a documents .yaml which I'd like to render via Markdown:

```yaml
$title: My Document

blurb: >
    This is some long form copy that is split into multiple paragraphs.

    Here is the second paragraph.
```

Is it possible to render individual fields of a document with markdown by using some built in filter in the template?
