### ISSUE TITLE
Redirect controllers

### ISSUE THREAD

**Issue by jeremydw** [grow/grow#117]
- Add new RedirectController (in addition to RenderedController and StaticController)
- Add ability to specify redirects in podspec.yaml
- Add ability to manage + deploy redirects to GCS
- Probably need to support tracking redirects in deployment indexes as well

**Comment by jeremydw** [comment]
Here's the first revision of a proposed syntax for declaring redirects. Note how we support multiple "from"s that all go to the same destination. Destinations can be either paths (which can be paths or full URLs – basically anything that the `Location` header can be set to) – OR content documents, whose URLs can be derived.

```
redirects:
- from:
  - path: /foo
  - path: /bar
  to:
    path: /qaz
- from:
  - path: /baz
  to:
    doc: /content/pages/home.yaml
- from:
  - path: /bee
  to:
    path: http://www.example.com
```
