### ISSUE TITLE
Translation request workflow

### ISSUE THREAD

**Issue by jeremydw** [grow/grow#131]
`grow machine_translate` should be refactored into a more generic translation request command that allows users to acquire translations through external services. We should support single command integration with services like Google Translate, Google Translator Toolkit, and other handy ones like POEditor.com or Gengo.

**Comment by jeremydw** [comment]
5c91693 kicks off the work for a translation request flow and "translator" backends. This enables the following sort of command to be run:

```
grow upload_translations <translator name>
```

Like deployments, the `<translator name>` of translators is user-configurable in `podspec.yaml` and users may place translator-specific configuration there.

For example:

```
# podspec.yaml
translators:
  gtt:
    translator: google_translator_toolkit
    project_title: "My Marketing Site"  # Optional (specific for google_translator_toolkit).
    acl:  # Optional (specific for google_translator_toolkit).
    - email: user@example.com
```

After the `upload_translations` command is implemented, we may need a way to store data provided in the responses from the translator backends. For example, in GTT's case, we can have Grow store and manage references to the GTT documents that it uploads in order to implement a kind-of distributed translation request system.

In GTT's case, if translation requests are invoked by a web application like webreview, the application's service account can have admin access on all of the documents and re-share as necessary to avoid requiring users to manually share documents. The same can be implemented for a translator backend like POEditor.com.
