### ISSUE TITLE
Google Cloud Storage preprocessor

### ISSUE THREAD

**Issue by jeremydw** [grow/grow#132]
It'd be handy to have an integration that allows us to generate YAML files based on metadata and files that exist in Google Cloud Storage. The integration would be similar to the Google Sheets preprocessor. Ideally, the same preprocessor could be adapted for S3 in addition to GCS.

**Comment by jeremydw** [comment]
Exploring a possible syntax for the GCS preprocessor.

```
- kind: gcs
  path: /data/assets.yaml
  bucket: example.com
  prefix: assets/foo/bar
  update_acl: publicRead
  generate_thumbnails:
    path: /source/images/thumbnails/
    size: [200, 200]
```
