### ISSUE TITLE
Implement builtin support for partials

### ISSUE THREAD

**Issue by jeremydw** [grow/grow#163]
There are several ways folks currently implement partials (templates, data, styles). We should spec out and implement a canonical way for folks to use partials to build pages.

**Comment by jeremydw** [comment]
Add a new top-level directory `/partials/`.

```
/partials/
  /hero/
    _blueprint.yaml
    hero.html
    hero.sass
```

Inside content files:

```
$partials:
- partial: hero
  title: Hello World
  cta:
    title: Click here
    url: http://www.example.com/
```

In the template:

```
doc.partials   # Not really happy with this, supposed to be similar to {{doc.html}}.
```

**Comment by jeremydw** [comment]
Some more thoughts (rough notes):

```
# /partials/hero/hero.html

{# Maybe some way to document the arguments here? #}
{% macro partial(title, subtitle) %}
  <h1 class=“hero__title”>{{title}}</h1>
  <p clas=“hero__subtitle”>{{subtitle}}</p>
{% endmacro %}

# /partials/hero/hero.sass

.hero

  .hero__title
    color: red

  .hero__subtitle
    color: blue

# /content/documents/home.yaml

$partials:
- partial: hero
  title: Hello World
  subtitle: Example

# Ways to render or access the partials in the template … TBD

{{doc.partials.hero(doc.partials.title, doc.partials.cta)}})
{{doc.render_partials(‘hero’)}}
```

**Comment by mhchen** [comment]
@jeremydw having now implemented the same pattern in 3 projects, have you given any more thoughts about how you want the syntax to look? I feel like maybe something like {{doc.partials_html}} in the template file might be okay. Is there a reason you were against {{doc.partials}}?

I also found it really beneficial to have the concept of nested partials, so something like:

```
$partials:
- partial: section
  title: Foo
  $subpartials:
  - partial: subsection
    title: Bar
```

I can take on the implementation if you have a syntax that you feel comfortable with.
