### ISSUE TITLE
Add parameter to `g.static` that changes the behavior of localized URL generation

### ISSUE THREAD

**Issue by jeremydw** [grow/grow#168]
Currently, `g.static` only creates localized URLs for static files if the localized static file exists. We can add a new flag that changes the behavior, allowing you to generate localized URLs for static files even if the static file is not localized.

To decide:
- Whether the flag should be on `g.static` or its `url` callable.
- Name of flag.

Some quick options:

```
# Default (generates localized URL if the file exists, root URL if it does not.)
{{g.static('/source/images/file.png', locale=doc.locale).url.path}}

# New behavior: localized=False on the url callable, generates root URL always.
{{g.static('/source/images/file.png', locale=doc.locale).url(localized=false).path}}

# New behavior: localized=True on the url callable, generates localized URL always.
{{g.static('/source/images/file.png', locale=doc.locale).url(localized=true).path}}
```

**Comment by Zoramite** [comment]
Instead of part of the usage in the template, this seems like it would be something better suited at the podspec level.

Something like?:

```yaml
# podspec.yaml
static_dirs:
- static_dir: /source/assets/images/
  serve_at: /assets/images/
  localization:
    static_dir: /source/assets/images/intl/{locale}/
    serve_at: /assets/images/intl/{locale}/
    ignore_missing: true
```
