### ISSUE TITLE
Allow overriding of default_locale content

### ISSUE THREAD

**Issue by WillsB3** [grow/grow#180]
Say I have this document:

```yaml
$localization:
  default_locale: en_us
  locales: 
    - en_gb
    - en_us
    - fr_fr

sections:
  header:
    text@: "Some header text"
  promo:
    heading@: "Heading"
```

The following does not work (and I kind of get why, since the default_locale document is the "base" document, and you can't specify a locale override more than once...) but it feels like it should:

```yaml
$localization:
  default_locale: en_us
  locales: 
    - en_gb
    - en_us
    - fr_fr

sections:
  header:
    text@: "Some header text"
  promo:
    heading@: "Heading"

---
$locale: en_us
  something_not_in_the_base_document: "Hi!"
```

Currently, the override content for `en_us` above is ignored, because the locale I'm trying to override is the same as the default locale. I feel like the "default" document should be more of an abstract thing, and not be tied so specifically to the default locale (if that makes sense).

Wondering if this impacts/is impacted by #142...
