### ISSUE TITLE
Disallow document parts without locales declared (maybe all overrides?)

### ISSUE THREAD

**Issue by stucox** [grow/grow#206]
Currently, if you have the following HTML / Markdown document:

```yaml
---
# front matter 1
---
Main body
---
# front matter 2
---
New body
---
```

“New body” will silently override “Main body” for all locales. I think this should throw an error — as there’s no obvious reason why someone would intentionally do this.

Similarly:

```yaml
---
$localization:
  locales:
    - en
    - fr
---
$locale: en
foo: 1
---
foo: 2
---
```

`foo` will equal 2 for both `en` and `fr` locales here. The chances are this would be a mistake: if the developer meant for `foo` to equal 2 for just `fr`, he/she should have put that in the main document front matter.

---

## Slightly more contentious cases:

```yaml
---
$localization:
  locales:
    - en
    - fr
---
$locale: en
foo: 1
---
$locale: en
foo: 2
---
```

I’d like to see an error here too. There’s clearly redundant code.

Although I know some Grow users would like more complex multiple-overrides to be possible, e.g.:

```yaml
---
$localization:
  locales:
    - en
    - fr
    - de
foo: 1
bar: 1
---
$locales:
  - en
  - fr
foo: 2
bar: 2
---
$locale: en
foo: 3
---
```

I believe @willsb3 and co would like this to result in `foo = 3` and `bar = 2` for `en`, `foo = 2` and `bar = 2` for `fr`, etc: i.e. values would be merged, so this can be used as a method of managing complex variation between locales without repetition…… but I’d also like to see an error in this case, because:

- It would be consistent with throwing an error for the previous (clearly redundant code) case
- I favour composition over inheritance, so would rather see common values defined in the top front matter & included into locale-specific sections without overriding

---

Hidden agenda: working on #204, if cases like this were disallowed, it also gives fewer cases which need to be defined/covered/tested… 😄
