### ISSUE TITLE
Discrepancy between staging paths and `grow build` paths

### ISSUE THREAD

**Issue by drGrove** [grow/grow#219]
When using `!g.url` within yaml and improperly referencing within the view. Staged and local run versions of the application properly route. But when built using `grow build` the paths don't align.
### Example:

``` yaml
# /content/globals.yaml
...

navigation:
  - title: "About"
    url: "#about-us"
    id: "about-us"
  - title: "Contact Us"
    url: !g.url /content/pages/contact-us.yaml
    id: "contact-us"
```

``` html
    <ul class="nav">
          {% for nav in globals.navigation %}
            <li aria-label="{{ _(nav.title) }}" title="{{ _(nav.title) }}" >
              <a href="{{ nav.url }}" id="{{ nav.id }}">
                {{ _(nav.title) }}
              </a>
            </li>
          {% endfor %}
        </ul>
```
#### Staging/Local

``` html
    <ul class="nav">
            <li aria-label="About" title="About" >
              <a href="#about-us" id="about-us">
                About
              </a>
            </li>
           <li aria-label="Contact Us" title="Contact Us" >
              <a href="http://.../contact-us" id="contact-us">
                About
              </a>
            </li>
        </ul>
```
#### Grow Build

``` html
    <ul class="nav">
            <li aria-label="About" title="About" >
              <a href="#about-us" id="about-us">
                About
              </a>
            </li>
           <li aria-label="Contact Us" title="Contact Us" >
              <a href="http://localhost/contact-us" id="contact-us">
                About
              </a>
            </li>
        </ul>
```

I realized what I actually needed in the html template was:

``` html
...
 <a href="{{ nav.url.path or nav.url }}" ...>
...
```

Since I using `!g.url` and just a string, but feel that `grow build` should be able to catch this
