### ISSUE TITLE
Grow won't share YAML node anchor references across front matters

### ISSUE THREAD

**Issue by elhesuu** [grow/grow#223]
YAML Node anchors are really useful to define base content and override for specific use cases.

Localisation may be the most common aspect that could benefit from this, as it would give the ability to override specific fields of a larger data structure, e.g.:

```YAML
item: &reference_name
  some_property: Foo
  another_property: Bar

---
$locale: en_GB

item:
  <<: *reference_name
  some_property: Baz
```

Defining content this way is perfect to avoid duplication and make localisation overrides stand out.
Sadly Grow doesn't seem to be sharing references between front matters, making it impossible to use this feature.
