### ISSUE TITLE
Configurable Markdown options

### ISSUE THREAD

**Issue by jeremydw** [grow/grow#246]
Grow makes a few assumptions about Markdown. We should provide the ability for developers to customize how Markdown is treated, similar to how Jekyll permits Markdown configuration (https://jekyllrb.com/docs/configuration/).

A sample configuration to change the `classes `option on the `sourcecode` extension:

```
markdown:
  extensions:
    sourcecode:
      classes: false
```

We could also have an option to change the parser, etc. if desired.

**Comment by jeremydw** [comment]
Fleshing this out a bit more, here's a fuller example where users can both specify third-party Markdown extensions and also configure them:

```
extensions:
[... other extensions, e.g. jinja2 or preprocessors ...]
  markdown:
  - extensions.markdown.FooBar

markdown:
  extensions:
  - kind: sourcecode
    classes: false
  - kind: foo_bar  # Defined by extension, just like preprocessors.
    qaz: qux
```

**Comment by vitorio** [comment]
Related to this, I was looking to see if there was a way configure the output of the TOC extension for a particular document, but at the podspec or collection level might be okay too.

**Comment by jeremydw** [comment]
Sure, let's add options that permit customize the TOC behavior. What sort of customization should we permit?

**Comment by vitorio** [comment]
The TOC extension defines its behavior at a higher level than the template: https://pythonhosted.org/Markdown/extensions/toc.html

I was looking to do something like:

```
markdown:
  extensions:
  - kind: toc
    baselevel: 2
    anchorlink: true
    permalink: true
```

This is the only document I've looked to automatically generate a TOC for so far, so I don't know how often I'd want to duplicate or change these options, but I can imagine it being useful at the document level.
