### ISSUE TITLE
Allow specific pages to be excluded from sitemap

### ISSUE THREAD

**Issue by stucox** [grow/grow#258]
Could there be an option to exclude specific files from the sitemap? For those times you want to launch something sensitive early but don’t want crawlers to find it just yet…

e.g.:

```
# content/pages/amazing-new-product.yaml
$sitemap: false
```

Or 

```
# podspec.yaml
sitemap:
  enabled: yes
  path: /{root}/sitemap.xml
  exclude:
    - content/pages/amazing-new-product.yaml
```

I appreciate you can tell podspec to only include specific collections, but the decision to show/hide might not tie up with the pod’s collection structure.

Don’t think both syntaxes are needed… the latter might be slightly more flexible if you combine it with anchors or something though (can’t think of a specific use case though!)
