### ISSUE TITLE
Allow to disable pygment

### ISSUE THREAD

**Issue by bluzky** [grow/grow#272]
Currently, user cannot use other highlight libraries (prismjs, highlightjs, ...)
We should add an option for markdown to disable pygment syntax highlighting.
Just put code in
```html
<pre>
    <code class="language-name">
        <!-- source code-->
    </code>
</pre>
```

**Comment by jeremydw** [comment]
Thanks for filing this, in our next release we will have the following option in podspec:

```
markdown:
  extensions:
  - kind: sourcecode
     highlighter: plain
```

And that will return HTML like `<pre><code class="language">... code ...</code></pre>` just as you described.
