### ISSUE TITLE
Discrepancy in string override behaviour between 0.65 vs 0.66

### ISSUE THREAD

**Issue by WillsB3** [grow/grow#279]
I'm testing a build with 0.66, but I have a discrepancy with a localized string. Our base doc has:

```
$localization:
 default_locale: en_US
 locales:
    - .. lots of locales..
    - ja_JP

$title: "Base Title"
```

Then we have a locale override:

```
---
$locale: ja_JP
$title@: "Title for ja_JP"
```

Now, the title for the page rendered for ja_JP is equal to "Base Title", not "Title for ja_JP". If I change the override to this:

```
---
$locale: ja_JP
$title: "Title for ja_JP"
```

It seems to fix it... Feels like a bug though, because now "Title for ja_JP" won't be extracted when running grow extract (I assume...)?
