### ISSUE TITLE
`grow extract --localized` doesn't behave correctly for subcollections

### ISSUE THREAD

**Issue by stucox** [grow/grow#289]
Looks like `grow extract --localized` extracts terms in docs in subcollections for all podspec locales, rather than the locales declared by the nearest blueprint (which is what I’d expect).

I’m afraid I haven’t had time to create a test case yet, but I have a structure similar to:

```
/
├─ content/
│   ├─ mycollection/
│   │   └─ mysubcollection/
│   │       ├─ _blueprint.yaml
│   │       └─ mydoc.yaml
│   :
├─ podspec.yaml
:
```

where:

* `mydoc.yaml` doesn’t declare a `$localization` config

* `_blueprint.yaml` declares:

    ```yaml
    localization:
      default_locale: en_US
      locales:
        - de_DE
        - en_US
    ```

* podspec.yaml declares

    ```yaml
    localization:
      default_locale: en_US
      locales:
        - de_DE
        - en_US
        - fr_FR
    ```

Tagged strings in `mydoc.yaml` are unexpectedly extracted for `fr_FR`.
