### ISSUE TITLE
Locale groups

### ISSUE THREAD

**Issue by jeremydw** [grow/grow#308]
There should be a way to specify locale groups to reduce duplication and centralize locale/feature management.

Some sample syntax:

```
localization:
  groups:
    foo:
    - de_DE
    - fr_CA
    bar:
    - ja_JP
    - ko_KR
```

And then it should be possible to refer to those groups where one would normally refer to a list of locales.

**Comment by stucox** [comment]
Rather than adding a new, specific feature, could this be achieved by just making existing YAML handling more flexible?

e.g. I think this already works:

```yaml
# my_doc.yaml
$localization:
  locales: !g.yaml locales/foo.yaml
```

Means you need a separate YAML file per group, but probably no drama. This would be nice:

```yaml
# my_doc.yaml
$localization:
  locales: !g.yaml locales.yaml:foo  # attaches the value of the `foo` property
```

Hopefully this kind of stuff might be possible too:

```yaml
# my_doc.yaml
$localization:
  locales:
    # This page is available in all `foo` and `bar` locales
    <<: !g.yaml locales.yaml:foo
    <<: !g.yaml locales.yaml:bar
```

— and if these extensions worked wherever you might use `g.yaml`, it could solve all sorts of other problems too.
