### ISSUE TITLE
Content split issue in 0.1.2

### ISSUE THREAD

**Issue by stevenle** [grow/grow#407]
Having an issue with localized content split into different files. Only able to reproduce on Ubuntu, not sure how that might affect things. Works fine in 0.0.68 but not in 0.1.2.

Steps to replicate (on Ubuntu):

* Start a virtualenv and pip install grow
```bash
virtualenv ~/venv
source ~/venv/bin/activate
pip install grow==0.1.2
grow --version
```

* Clone the codelab
```bash
grow init codelab ./my-codelab/
```

* Create `/content/pages/index@pt_br.md` and add the following content:
```yaml
---
$title@: Welcome pt_br

icon: home
tagline: Lorem ipsum dolor pt_br
---
This is pt_br content.
```

* Deploy the site
```bash
grow deploy -f
```

Then check the contents at `my-codelab-launch/pt_br/index.html` and you'll notice the en content is used.

However, if you `pip uninstall grow` then `pip install grow==0.0.68` and `grow deploy -f` you'll notice the correct pt_br content is used.
