### ISSUE TITLE
Add fields to sheets translator

### ISSUE THREAD

**Issue by stevenle** [grow/grow#419]
At the moment, the sheets translator only uploads the string, translation, and file location. I have a use-case for a project that requires a "key" and translator comments. For the "key", would be good enough to use some hash of the string. 

It'd be cool to be able to configure the sheets translator to optionally add additional fields, maybe something like:

```
translators:
  - service: google_sheets
    acl:
    - domain: blinkk.com
      role: WRITER
    extra_fields:
    - md5_hash
    - translator_comments
```

LMK what you think.
