### ISSUE TITLE
Translator comments for yaml list of strings

### ISSUE THREAD

**Issue by stevenle** [grow/grow#426]
Not sure if there's already a way to input translator comments for yaml lists, but I tried the following and it didn't work:

```yaml
role_select@#: "Dropdown value for the role of a restaurant employee."
role_select@:
- Owner
- General Manager
- On-Site Manager
- Marketing
- Accounting
- Chef
- Front of House
- Other
```

I switched to this temporarily, but would be great to support the syntax above.

```yaml
role_select:
- name@#: "Dropdown value for the role of a restaurant employee."
  name@: "Owner"
- name@#: "Dropdown value for the role of a restaurant employee."
  name@: "General Manager"
- name@#: "Dropdown value for the role of a restaurant employee."
  name@: "On-Site Manager"
- name@#: "Dropdown value for the role of a restaurant employee."
  name@: "Marketing"
- name@#: "Dropdown value for the role of a restaurant employee."
  name@: "Accounting"
- name@#: "Dropdown value for the role of a restaurant employee."
  name@: "Chef"
- name@#: "Dropdown value for the role of a restaurant employee."
  name@: "Front of House"
- name@#: "Dropdown value for the role of a restaurant employee."
  name@: "Other"
```
