### ISSUE TITLE
Locale value overrides with default_locale

### ISSUE THREAD

**Issue by stevenle** [grow/grow#448]
I think there might be an issue with localized values and default_locale. In the following snippet, I'd expect "French value" to be output, but I think it actually outputs "Default value".

```yaml
# doc.yaml

$localization:
  default_locale: fr

foobar@: Default value
foobar@fr: French value
```

```jinja
{# view.html #}

{{_(doc.foobar)}}
```

One way I was able to quickly reproduce was to `grow init codelab ./my-codelab/` and then change `default_locale` and `tagline` in index.md.
