### ISSUE TITLE
Conditional YAML based on environment name

### ISSUE THREAD

**Issue by jeremydw** [grow/grow#464]
In templates, we can change things based on `{{env.name}}` but it would be nice to add support for changing YAML data dynamically too. For example - this could be used to change API keys for integrations, conditionally update paths based on the build env, etc.

In particular, I am interested in using it for our CMS integrations (such as https://github.com/grow/grow-ext-kintaro) so that we can pull `draft` content on the dev and staging environments and pull only `published` content for production builds.

Sample syntax (current proposal overloads the `@` syntax with `@env.<name>`).

```
# podspec.yaml
meta:
  api_key: foo
  api_key@env.prod: bar

deployments:
  prod:
    kind: local
    out_dir: ./build/
    env:
      name: prod
```

Resulting in...

```
{{podspec.meta.api_key}} -> foo   # On the dev server.
{{podspec.meta.api_key}} -> bar   # When using `grow deploy prod`.
```
