### ISSUE TITLE
Sheets preprocessor not running without gid

### ISSUE THREAD

**Issue by stevenle** [grow/grow#538]
Updated to latest grow and I think there was a regression with the sheets preprocessor -- when a gid isn't provided, it used to default to gid=0, but now it looks like it needs to be manually specified.

Steps to replicate:

```
# podspec.yaml
preprocessors:
- name: events
  kind: google_sheets
  path: /data/events.json
  output_style: pretty
  id: <insert sheet id>
  autorun: false
```

Running `grow preprocess -p events` doesn't seem to display any error messages.
