### ISSUE TITLE
Issue with --re-route and localized static files

### ISSUE THREAD

**Issue by stevenle** [grow/grow#684]
Some strange things going on with localized static files and the new experimental `--re-route` flag. Here's an example from an actual project:

Podspec:

```
- static_dir: /source/assets/images/
  serve_at: /assets/images/
  localization:
    static_dir: /source/assets/images/intl/{locale}/
    serve_at: /assets/images/intl/{locale}/
```

Expected: `/assets/images/agora/yuzu/phone-shell.png`
Actual: `/assets/images/intl/en/ne-shell.png`
