### ISSUE TITLE
New routing giving error when running locally.

### ISSUE THREAD

**Issue by angusm** [grow/grow#787]
Using the following podspec.yaml locales config:

```
localization:
  default_locale: en_US
  extract:
    localized: true
  locales:
    - de_DE
    - en_CA
    - en_GB
    - en_US
    - es_419
    - es_ES
    - fr_FR
    - fr_CA
    - hi_IN
    - it_IT
    - ja_JP
    - pt_BR
    - pt_PT
  aliases:
    de_ALL: de_DE
    en_CA: en_CA
    en_UK: en_GB
    es-419_ALL: es_419
    es_ALL: es_ES
    fr_ALL: fr_FR
    fr_CA: fr_CA
    hi_ALL: hi_IN
    it_ALL: it_IT
    ja_ALL: ja_JP
    pt-BR_ALL: pt_BR
    pt-PT_ALL: pt_PT
  import_as:
    de:
    - de_DE
    en-GB:
    - en_CA
    - en_GB
    es:
    - es_ES
    - es_PR
    es-419:
    - es_419
    fr:
    - fr_FR
    - fr_CA
    hi:
    - hi_IN
    id:
    - id_ID
    it:
    - it_IT
    ja:
    - ja_JP
    pt-BR:
    - pt_BR
    pt-PT:
    - pt_PT
```

When viewing routes at http://localhost:8080/_grow/routes

A route such as `/intl/hi_ALL/something/something` will appear, but when following through the link I am presented with the `Something went wrong while building this page.` error page, telling me `/intl/hi_ALL/something/something not found`.

This error does not appear when kicking off to staging using CircleCI `grow build` and `grow stage`.

Running grow build locally produces the expected files as well.

The issue does not appear when running `grow run --old-routing`.
