### ISSUE TITLE
Support for referencing locale groups

### ISSUE THREAD

**Issue by Zoramite** [grow/grow#837]
Currently when doing tagged localization it can be quite repetitive when using locale groups.

For example: 

```yaml
text@(de_DE_|en_GB|en_US|fr_CA_|fr_FR|ja_JP): something
other@(de_DE_|en_GB|en_US|fr_CA_|fr_FR|ja_JP): else
```

Instead we can use an identifier to reference a locale regex, similar to how environment tagging is done (ex: `text@env.prod`).

The regex could be defined in the document or fallback to the podspec.

```yaml
$localization:
  groups:
    locale_group:
    - de_DE
    - en_GB
    - en_US
    - fr_CA
    - fr_FR
    - ja_JP

text@locale.locale_group: something
other@locale.locale_group: else
```

or

```yaml
# podspec.yaml
localization:
  default_locale: en_US
  groups:
    group1: de_DE_|en_GB|en_US|fr_CA_|fr_FR|ja_JP
```

```yaml
# content/pages/about.yaml
text@locale.group1: something
other@locale.group1: else
```
