### ISSUE TITLE
Experiments in Grow

### ISSUE THREAD

**Issue by Zoramite** [grow/grow#866]
Allow for defining `experiments` to enable in grow in the `podspec`. The actual implementation can use the pod features to turn on and off and optionally provide settings for the experiment.

Ex:

```yaml
experiments:
  collection_routes: true
  unusual_routing: 
    setting: true
```
