### ISSUE TITLE
Allow arbitrary data in podspec's env

### ISSUE THREAD

**Issue by matthiasrohmer** [grow/grow#926]
It might be that there's a specific reason that the `env` global only holds host, port name and scheme and drops everything else but for a recent project we've been doing we needed to have different settings per  environment which currently isn't supported. We've then done the following in the template instead:

```
{% set cdn_host = podspec.cdn_hosts[env.name] or podspec.cdn_host %}
```

This of course also works, but is not as nice 😉

**Comment by jeremydw** [comment]
Hi! We actually support YAML tagging with environment names – for this very purpose. :)

So if you have this in `podspec.yaml`:

```
meta:
  cdn_host: cdn-dev.com
  cdn_host@env.prod: cdn-prod.com

deployments:
  prod:
    destination: local
    out_dir: ./build/
    env:
      name: prod
```

`{{podspec.meta.cdn_host}}` will return what you might expect (cdn-dev.com on the dev server and cdn-prod.com when you do `grow deploy -f prod`
